"""Upgrade / research catalog — engine research times + GM-curated tech requirements.

The engine's UpgradeData gives authoritative research_time and cost, but NOT which
building researches an upgrade or its prerequisites. Those are GM-known and curated in
REQUIREMENTS. load_upgrades() merges the two into BuildItems the timing calculator can
schedule: kind='upgrade', built_by=<research building> (occupied for the research
duration), requires=<prereq buildings/upgrades that must exist first>.

Weapon/armor lines (L1/L2/L3) are generated by _levels() so the tier-2/3 building and
the prior-level prereq are consistent. Ability upgrades are listed explicitly.

Deferred (see TODO.md): PsiStorm (TemplarArchives not in the unit dump under that name),
and a handful of co-op-only upgrades. Names not present in a given era's dump are skipped.
"""

import json
from pathlib import Path

from .build_data import BuildItem


def _levels(prefix, race, building, tier2=None, tier3=None, alias=""):
    """Generate L1/L2/L3 entries. L2 needs tier2 (if any) + L1; L3 needs tier3-or-tier2 + L2."""
    out = {}
    for lvl in (1, 2, 3):
        pre = []
        if lvl == 2 and tier2:
            pre.append(tier2)
        if lvl == 3 and (tier3 or tier2):
            pre.append(tier3 or tier2)
        if lvl >= 2:
            pre.append(f"{prefix}Level{lvl - 1}")
        out[f"{prefix}Level{lvl}"] = (race, building, tuple(pre), f"+{lvl} {alias}")
    return out


# engine_name: (race, researched_at, prereqs, friendly_alias)
REQUIREMENTS = {}

# --- weapon / armor (all races, L1-3) ----------------------------------------
REQUIREMENTS.update(_levels("ProtossGroundWeapons", "Protoss", "Forge", "TwilightCouncil", alias="ground attack"))
REQUIREMENTS.update(_levels("ProtossGroundArmors", "Protoss", "Forge", "TwilightCouncil", alias="ground armor"))
REQUIREMENTS.update(_levels("ProtossShields", "Protoss", "Forge", "TwilightCouncil", alias="shields"))
REQUIREMENTS.update(_levels("ProtossAirWeapons", "Protoss", "CyberneticsCore", "FleetBeacon", alias="air attack"))
REQUIREMENTS.update(_levels("ProtossAirArmors", "Protoss", "CyberneticsCore", "FleetBeacon", alias="air armor"))

REQUIREMENTS.update(_levels("TerranInfantryWeapons", "Terran", "EngineeringBay", "Armory", alias="infantry attack"))
REQUIREMENTS.update(_levels("TerranInfantryArmors", "Terran", "EngineeringBay", "Armory", alias="infantry armor"))
REQUIREMENTS.update(_levels("TerranVehicleWeapons", "Terran", "Armory", alias="vehicle attack"))
REQUIREMENTS.update(_levels("TerranShipWeapons", "Terran", "Armory", alias="ship attack"))
REQUIREMENTS.update(_levels("TerranVehicleAndShipArmors", "Terran", "Armory", alias="vehicle/ship plating"))

REQUIREMENTS.update(_levels("ZergMeleeWeapons", "Zerg", "EvolutionChamber", "Lair", "Hive", alias="melee attack"))
REQUIREMENTS.update(_levels("ZergMissileWeapons", "Zerg", "EvolutionChamber", "Lair", "Hive", alias="ranged attack"))
REQUIREMENTS.update(_levels("ZergGroundArmors", "Zerg", "EvolutionChamber", "Lair", "Hive", alias="ground carapace"))
REQUIREMENTS.update(_levels("ZergFlyerWeapons", "Zerg", "Spire", "Lair", "Hive", alias="flyer attack"))
REQUIREMENTS.update(_levels("ZergFlyerArmors", "Zerg", "Spire", "Lair", "Hive", alias="flyer armor"))

# --- ability / unit upgrades -------------------------------------------------
_ABILITIES = {
    # Protoss
    "WarpGateResearch": ("Protoss", "CyberneticsCore", (), "warpgate"),
    "Charge": ("Protoss", "TwilightCouncil", (), "charge"),
    "BlinkTech": ("Protoss", "TwilightCouncil", (), "blink"),
    "AdeptPiercingAttack": ("Protoss", "TwilightCouncil", (), "resonating glaives (adept)"),
    "DarkTemplarBlinkUpgrade": ("Protoss", "DarkShrine", (), "shadow stride (dt blink)"),
    "PsiStormTech": ("Protoss", "TemplarArchive", (), "psionic storm (high templar)"),
    "ExtendedThermalLance": ("Protoss", "RoboticsBay", (), "colossus range"),
    "GraviticDrive": ("Protoss", "RoboticsBay", (), "warp prism speed"),
    "ObserverGraviticBooster": ("Protoss", "RoboticsBay", (), "observer speed"),
    "PhoenixRangeUpgrade": ("Protoss", "FleetBeacon", (), "anion pulse-crystals (phoenix range)"),
    "VoidRaySpeedUpgrade": ("Protoss", "FleetBeacon", (), "flux vanes (void ray speed)"),
    "CarrierLaunchSpeedUpgrade": ("Protoss", "FleetBeacon", (), "graviton catapult (carrier)"),
    # Terran
    "Stimpack": ("Terran", "BarracksTechLab", (), "stim"),
    "ShieldWall": ("Terran", "BarracksTechLab", (), "combat shield"),
    "PunisherGrenades": ("Terran", "BarracksTechLab", (), "concussive shells"),
    "HighCapacityBarrels": ("Terran", "FactoryTechLab", (), "infernal pre-igniter (hellion)"),
    "DrillClaws": ("Terran", "FactoryTechLab", (), "drilling claws (widow mine)"),
    "SmartServos": ("Terran", "FactoryTechLab", (), "smart servos (transform)"),
    "CycloneLockOnDamageUpgrade": ("Terran", "FactoryTechLab", (), "mag-field accelerators (cyclone)"),
    "BansheeCloak": ("Terran", "StarportTechLab", (), "cloaking field (banshee)"),
    "BansheeSpeed": ("Terran", "StarportTechLab", (), "hyperflight rotors (banshee speed)"),
    "LiberatorAGRangeUpgrade": ("Terran", "StarportTechLab", (), "advanced ballistics (liberator)"),
    "MedivacIncreaseSpeedBoost": ("Terran", "StarportTechLab", (), "medivac afterburners"),
    "RavenCorvidReactor": ("Terran", "StarportTechLab", (), "raven energy"),
    "InterferenceMatrix": ("Terran", "StarportTechLab", (), "interference matrix (raven)"),
    "PersonalCloaking": ("Terran", "GhostAcademy", (), "ghost cloak"),
    "HiSecAutoTracking": ("Terran", "EngineeringBay", (), "hi-sec auto tracking"),
    "NeosteelFrame": ("Terran", "EngineeringBay", (), "neosteel armor"),
    "BattlecruiserEnableSpecializations": ("Terran", "FusionCore", (), "yamato / tactical jump"),
    # Zerg
    "zerglingmovementspeed": ("Zerg", "SpawningPool", (), "metabolic boost (ling speed)"),
    "zerglingattackspeed": ("Zerg", "SpawningPool", ("Hive",), "adrenal glands (ling attack speed)"),
    "GlialReconstitution": ("Zerg", "RoachWarren", (), "glial reconstitution (roach speed)"),
    "TunnelingClaws": ("Zerg", "RoachWarren", (), "tunneling claws (roach)"),
    "CentrificalHooks": ("Zerg", "BanelingNest", (), "centrifugal hooks (bane speed)"),
    "EvolveMuscularAugments": ("Zerg", "HydraliskDen", (), "muscular augments (hydra speed)"),
    "EvolveGroovedSpines": ("Zerg", "HydraliskDen", (), "grooved spines (hydra range)"),
    "LurkerRange": ("Zerg", "LurkerDenMP", (), "seismic spines (lurker range)"),
    "DiggingClaws": ("Zerg", "LurkerDenMP", (), "adaptive talons (lurker burrow)"),
    "NeuralParasite": ("Zerg", "InfestationPit", (), "neural parasite (infestor)"),
    "ChitinousPlating": ("Zerg", "UltraliskCavern", (), "chitinous plating (ultra)"),
    "AnabolicSynthesis": ("Zerg", "UltraliskCavern", (), "anabolic synthesis (ultra speed)"),
    "overlordspeed": ("Zerg", "Hatchery", (), "pneumatized carapace (overlord speed)"),
    "overlordtransport": ("Zerg", "Lair", (), "ventral sacs (overlord transport)"),
    "Burrow": ("Zerg", "Hatchery", (), "burrow"),
}
REQUIREMENTS.update(_ABILITIES)


def load_upgrades(dump_path, race=None):
    """Build {engine_name: BuildItem(kind='upgrade')} merging engine times with REQUIREMENTS."""
    data = json.loads(Path(dump_path).read_text())
    by_name = {u["name"]: u for u in data.get("upgrades", [])}
    items = {}
    for ename, (r, bld, prereqs, _alias) in REQUIREMENTS.items():
        if race and r != race:
            continue
        u = by_name.get(ename)
        if u is None:
            continue  # not in this dump (era without the upgrade, or a name mismatch)
        items[ename] = BuildItem(
            name=ename, race=r, mineral_cost=u["mineral_cost"], gas_cost=u["gas_cost"],
            build_time_s=round(u["research_time_s"], 1), kind="upgrade",
            built_by=bld, requires=tuple(prereqs), time_verified=True)
    return items
